### ISSUE TITLE
Not working on deno deploy

### ISSUE THREAD

**Issue by divyam234** [kleisauke/wasm-vips#53]
```
ReferenceError: Worker is not defined
    at Object.nb (https://cdn.jsdelivr.net/npm/wasm-vips/lib/vips-es6.js:102:450)
    at Object.Fc (https://cdn.jsdelivr.net/npm/wasm-vips/lib/vips-es6.js:99:127)
    at Object.init (https://cdn.jsdelivr.net/npm/wasm-vips/lib/vips-es6.js:99:58)
    at https://cdn.jsdelivr.net/npm/wasm-vips/lib/vips-es6.js:348:221
    at file:///src/main.ts:11:20
```

**Comment by kleisauke** [comment]
It appears that Deno Deploy doesn't support the Web Workers API, see:
https://workers.js.org/#browser-apis

Given that wasm-vips requires this functionality to be available, I'll close this as "won't fix" for now. Please subscribe to  https://github.com/denoland/deploy_feedback/issues/171 for updates related to this.
