### ISSUE TITLE
Failure to Load Large PNG Images (e.g., 8K Resolution) in Node.js on Windows

### ISSUE THREAD

**Issue by kyouhei-horizumi** [kleisauke/wasm-vips#84]
When attempting to load large images, such as those with 8K resolution, the operation occasionally fails.

OS: Windows 11
Node.js: `v22.9.0`
wasm-vips: `0.0.11`

```js
import Vips from 'wasm-vips';

Vips().then((vips) => {
    const image = vips.Image.newFromFile('nc192085.png');
    image.jpegsave('nc192085.jpg');
}).catch(console.error);
```

```powershell
PS > node app.js
rb [vips::Error]: unable to call jpegsave
VipsImage: unable to write to "/tmp/vips-0-3093572251.v"
system error: No such file or directory

    at Fb (file:///.../node_modules/wasm-vips/lib/vips-node.mjs:58:43)
    at me (file:///.../node_modules/wasm-vips/lib/vips-node.mjs:216:270)
    at wasm://wasm/015f49d6:wasm-function[3980]:0x1a22de
    at ue (file:///.../node_modules/wasm-vips/lib/vips-node.mjs:218:356)
    at wasm://wasm/015f49d6:wasm-function[6012]:0x2b8b15
    at me (file:///.../node_modules/wasm-vips/lib/vips-node.mjs:216:270)
    at wasm://wasm/015f49d6:wasm-function[3253]:0x176546
    at he (file:///.../node_modules/wasm-vips/lib/vips-node.mjs:218:38)
    at wasm://wasm/015f49d6:wasm-function[4349]:0x1b9ab4
    at Image.jpegsave (eval at Sh (file:///.../node_modules/wasm-vips/lib/vips-node.mjs:153:241), <anonymous>:7:1) {
  ta: 9375224
}
```

nc192085.png
![nc192085](https://github.com/user-attachments/assets/aceae875-a9f2-42f1-894e-e12b5636c8b1)

## Notes

+ `vips.Image.newFromFile('small.png').jpegsave('small.jpg');` => OK
+ `vips-dev-8.16\bin\vips.exe jpegsave nc192085.png nc192085.jpg` => OK
+ on WSL2 (Ubuntu 22.04 / Node.js v22.5.1) => OK

**Comment by kleisauke** [comment]
The Wasm binary is somewhat POSIX-specific, so it doesn't recognize that it's running on a Windows system. By default, it uses the `/tmp` directory when libvips decompresses a large image (above 100MiB when decompressed) to a temporary file on the disk. You can adjust the threshold for open-via-memory versus open-via-disk using the `VIPS_DISC_THRESHOLD` environment variable. See for more information:
https://www.libvips.org/API/current/How-it-opens-files.html

To prevent the use of the `/tmp` directory, you can also set the `TMPDIR` environment variable to a different path, for example:
https://github.com/kleisauke/wasm-vips/blob/7fa9bf21b0eb95967558b5ecdd1b219cf8dcba1f/test/bench/perf.js#L23-L27

Alternatively, you can open the image in sequential access mode:
```diff
@@ -1,6 +1,8 @@
 import Vips from 'wasm-vips';
 
 Vips().then((vips) => {
-    const image = vips.Image.newFromFile('nc192085.png');
+    const image = vips.Image.newFromFile('nc192085.png', {
+      access: vips.Access.sequential // 'sequential'
+    });
     image.jpegsave('nc192085.jpg');
 }).catch(console.error);
```

Commit a50ff5e3f63eef9af9fa75210190f9836d8959b8 always sets the `TMPDIR` environment variable to `require('os').tmpdir()` on Node.js, this will be in v0.0.12. Thanks for reporting this!
